-- Migration 004: tabelas extras (pesquisas, eventos, conversas, movimentacoes, notificacoes, atividades)
-- Execute apos a 003. CREATE IF NOT EXISTS + seed idempotente.


CREATE TABLE IF NOT EXISTS `pesquisas` (
  `id` VARCHAR(40) PRIMARY KEY,
  `titulo` VARCHAR(200),
  `data` VARCHAR(40),
  `amostra` INT DEFAULT 0,
  `intencao` JSON,
  `perguntas` JSON
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `eventos` (
  `id` VARCHAR(40) PRIMARY KEY,
  `titulo` VARCHAR(200),
  `data` VARCHAR(40),
  `local` VARCHAR(200),
  `bairro` VARCHAR(120),
  `tipo` VARCHAR(60),
  `status` VARCHAR(40),
  `confirmados` INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `conversas` (
  `id` VARCHAR(40) PRIMARY KEY,
  `eleitor_id` VARCHAR(40),
  `nome` VARCHAR(120),
  `bairro` VARCHAR(120),
  `tags` JSON,
  `nao_lidas` INT DEFAULT 0,
  `online` TINYINT(1) DEFAULT 0,
  `mensagens` JSON
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `movimentacoes` (
  `id` VARCHAR(40) PRIMARY KEY,
  `descricao` VARCHAR(200),
  `categoria` VARCHAR(60),
  `tipo` VARCHAR(20),
  `valor` INT DEFAULT 0,
  `data` VARCHAR(40)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `notificacoes` (
  `id` VARCHAR(40) PRIMARY KEY,
  `titulo` VARCHAR(200),
  `corpo` TEXT,
  `tempo` VARCHAR(40),
  `lida` TINYINT(1) DEFAULT 0,
  `tipo` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `atividades` (
  `id` VARCHAR(40) PRIMARY KEY,
  `usuario` VARCHAR(120),
  `acao` VARCHAR(120),
  `alvo` VARCHAR(120),
  `tempo` VARCHAR(40),
  `tipo` VARCHAR(40)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `pesquisas` (`id`, `titulo`, `data`, `amostra`, `intencao`, `perguntas`) VALUES ('pesq-1', 'Intenção de voto — 1º turno', '2026-05-20T03:00:00.000Z', 1840, '[{"nome":"Candidato A (nosso)","valor":38},{"nome":"Candidato B","valor":29},{"nome":"Candidato C","valor":14},{"nome":"Branco/Nulo","valor":9},{"nome":"Indeciso","valor":10}]', '[{"pergunta":"Aprova avaliação do prefeito atual?","aprovacao":41},{"pergunta":"Segurança é prioridade?","aprovacao":88},{"pergunta":"Saúde é prioridade?","aprovacao":81},{"pergunta":"Conhece propostas do candidato A?","aprovacao":54}]');
INSERT IGNORE INTO `pesquisas` (`id`, `titulo`, `data`, `amostra`, `intencao`, `perguntas`) VALUES ('pesq-2', 'Rejeição por faixa etária', '2026-05-20T03:00:00.000Z', 920, '[{"nome":"16-24","valor":33},{"nome":"25-39","valor":42},{"nome":"40-59","valor":37},{"nome":"60+","valor":28}]', '[{"pergunta":"Usa redes sociais para política?","aprovacao":63},{"pergunta":"Confia em WhatsApp como fonte?","aprovacao":47}]');
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-1', 'Caminhada no bairro', '2026-02-02T03:00:00.000Z', 'Ginásio Municipal', 'Maiobao', 'Caminhada', 'confirmado', 37);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-2', 'Roda de conversa', '2026-03-03T03:00:00.000Z', 'Centro Comunitário', 'Tambau', 'Debate', 'confirmado', 54);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-3', 'Lançamento de candidatura', '2026-04-04T03:00:00.000Z', 'Clube dos Bancários', 'Vinhais', 'Social', 'realizado', 71);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-4', 'Carreata', '2026-05-05T03:00:00.000Z', 'Teatro Municipal', 'Calhau', 'Institucional', 'cancelado', 88);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-5', 'Café com lideranças', '2026-06-06T03:00:00.000Z', 'Quadra da Escola', 'Cohab', 'Comício', 'planejado', 105);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-6', 'Mutirão de limpeza', '2026-07-07T03:00:00.000Z', 'Praça da Sé', 'Anil', 'Caminhada', 'confirmado', 122);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-7', 'Audiência pública', '2026-08-08T03:00:00.000Z', 'Ginásio Municipal', 'Turu', 'Debate', 'confirmado', 139);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-8', 'Reunião de cabos', '2026-09-09T03:00:00.000Z', 'Centro Comunitário', 'Centro', 'Social', 'realizado', 156);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-9', 'Comício na Praça Central', '2026-01-10T03:00:00.000Z', 'Clube dos Bancários', 'Maiobao', 'Institucional', 'cancelado', 173);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-10', 'Caminhada no bairro', '2026-02-11T03:00:00.000Z', 'Teatro Municipal', 'Tambau', 'Comício', 'planejado', 190);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-11', 'Roda de conversa', '2026-03-12T03:00:00.000Z', 'Quadra da Escola', 'Vinhais', 'Caminhada', 'confirmado', 207);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-12', 'Lançamento de candidatura', '2026-04-13T03:00:00.000Z', 'Praça da Sé', 'Calhau', 'Debate', 'confirmado', 224);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-13', 'Carreata', '2026-05-14T03:00:00.000Z', 'Ginásio Municipal', 'Cohab', 'Social', 'realizado', 241);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-14', 'Café com lideranças', '2026-06-15T03:00:00.000Z', 'Centro Comunitário', 'Anil', 'Institucional', 'cancelado', 258);
INSERT IGNORE INTO `eventos` (`id`, `titulo`, `data`, `local`, `bairro`, `tipo`, `status`, `confirmados`) VALUES ('evt-15', 'Mutirão de limpeza', '2026-07-16T03:00:00.000Z', 'Clube dos Bancários', 'Turu', 'Comício', 'planejado', 275);
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-1', 'elt-2', 'Joo Souza', 'Maiobao', '["provavel","receptivo"]', 0, 'false', '[{"id":"m10","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"8:00"},{"id":"m11","de":"cabo","texto":"Pode me mandar o material?","hora":"9:07"},{"id":"m12","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"10:14"},{"id":"m13","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-2', 'elt-3', 'Ana Lima', 'Tambau', '["indeciso","prioridade"]', 0, 'true', '[{"id":"m20","de":"eleitor","texto":"Pode me mandar o material?","hora":"8:00"},{"id":"m21","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"9:07"},{"id":"m22","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"10:14"},{"id":"m23","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"11:21"},{"id":"m24","de":"eleitor","texto":"Obrigado pelas informações.","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-3', 'elt-4', 'Carlos Pereira', 'Vinhais', '["adversario","whatsapp"]', 4, 'false', '[{"id":"m30","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"8:00"},{"id":"m31","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"9:07"},{"id":"m32","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"10:14"},{"id":"m33","de":"cabo","texto":"Obrigado pelas informações.","hora":"11:21"},{"id":"m34","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"12:28"},{"id":"m35","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-4', 'elt-5', 'Beatriz Rocha', 'Calhau', '["ferrenho","receptivo"]', 0, 'true', '[{"id":"m40","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"8:00"},{"id":"m41","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"9:07"},{"id":"m42","de":"eleitor","texto":"Obrigado pelas informações.","hora":"10:14"},{"id":"m43","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"11:21"},{"id":"m44","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"12:28"},{"id":"m45","de":"cabo","texto":"Quando tem o próximo evento?","hora":"13:35"},{"id":"m46","de":"eleitor","texto":"Pode me mandar o material?","hora":"14:42"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-5', 'elt-6', 'Pedro Alves', 'Cohab', '["provavel","prioridade"]', 0, 'false', '[{"id":"m50","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"8:00"},{"id":"m51","de":"cabo","texto":"Obrigado pelas informações.","hora":"9:07"},{"id":"m52","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"10:14"},{"id":"m53","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"11:21"},{"id":"m54","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"12:28"},{"id":"m55","de":"cabo","texto":"Pode me mandar o material?","hora":"13:35"},{"id":"m56","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"14:42"},{"id":"m57","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"15:49"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-6', 'elt-7', 'Luisa Costa', 'Anil', '["indeciso","whatsapp"]', 3, 'true', '[{"id":"m60","de":"eleitor","texto":"Obrigado pelas informações.","hora":"8:00"},{"id":"m61","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"9:07"},{"id":"m62","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"10:14"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-7', 'elt-8', 'Felipe Dias', 'Turu', '["adversario","receptivo"]', 0, 'false', '[{"id":"m70","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"8:00"},{"id":"m71","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"9:07"},{"id":"m72","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"10:14"},{"id":"m73","de":"cabo","texto":"Pode me mandar o material?","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-8', 'elt-9', 'Juliana Martins', 'Centro', '["ferrenho","prioridade"]', 0, 'true', '[{"id":"m80","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"8:00"},{"id":"m81","de":"cabo","texto":"Quando tem o próximo evento?","hora":"9:07"},{"id":"m82","de":"eleitor","texto":"Pode me mandar o material?","hora":"10:14"},{"id":"m83","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"11:21"},{"id":"m84","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-9', 'elt-10', 'Rafael Oliveira', 'Maiobao', '["provavel","whatsapp"]', 2, 'false', '[{"id":"m90","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"8:00"},{"id":"m91","de":"cabo","texto":"Pode me mandar o material?","hora":"9:07"},{"id":"m92","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"10:14"},{"id":"m93","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"11:21"},{"id":"m94","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"12:28"},{"id":"m95","de":"cabo","texto":"Obrigado pelas informações.","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-10', 'elt-11', 'Camila Santos', 'Tambau', '["indeciso","receptivo"]', 0, 'true', '[{"id":"m100","de":"eleitor","texto":"Pode me mandar o material?","hora":"8:00"},{"id":"m101","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"9:07"},{"id":"m102","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"10:14"},{"id":"m103","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"11:21"},{"id":"m104","de":"eleitor","texto":"Obrigado pelas informações.","hora":"12:28"},{"id":"m105","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"13:35"},{"id":"m106","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"14:42"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-11', 'elt-12', 'Bruno Carvalho', 'Vinhais', '["adversario","prioridade"]', 0, 'false', '[{"id":"m110","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"8:00"},{"id":"m111","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"9:07"},{"id":"m112","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"10:14"},{"id":"m113","de":"cabo","texto":"Obrigado pelas informações.","hora":"11:21"},{"id":"m114","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"12:28"},{"id":"m115","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"13:35"},{"id":"m116","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"14:42"},{"id":"m117","de":"cabo","texto":"Pode me mandar o material?","hora":"15:49"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-12', 'elt-13', 'Maria Silva', 'Calhau', '["ferrenho","whatsapp"]', 1, 'true', '[{"id":"m120","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"8:00"},{"id":"m121","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"9:07"},{"id":"m122","de":"eleitor","texto":"Obrigado pelas informações.","hora":"10:14"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-13', 'elt-14', 'Joo Souza', 'Cohab', '["provavel","receptivo"]', 0, 'false', '[{"id":"m130","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"8:00"},{"id":"m131","de":"cabo","texto":"Obrigado pelas informações.","hora":"9:07"},{"id":"m132","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"10:14"},{"id":"m133","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-14', 'elt-15', 'Ana Lima', 'Anil', '["indeciso","prioridade"]', 0, 'true', '[{"id":"m140","de":"eleitor","texto":"Obrigado pelas informações.","hora":"8:00"},{"id":"m141","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"9:07"},{"id":"m142","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"10:14"},{"id":"m143","de":"cabo","texto":"Quando tem o próximo evento?","hora":"11:21"},{"id":"m144","de":"eleitor","texto":"Pode me mandar o material?","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-15', 'elt-16', 'Carlos Pereira', 'Turu', '["adversario","whatsapp"]', 4, 'false', '[{"id":"m150","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"8:00"},{"id":"m151","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"9:07"},{"id":"m152","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"10:14"},{"id":"m153","de":"cabo","texto":"Pode me mandar o material?","hora":"11:21"},{"id":"m154","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"12:28"},{"id":"m155","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-16', 'elt-17', 'Beatriz Rocha', 'Centro', '["ferrenho","receptivo"]', 0, 'true', '[{"id":"m160","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"8:00"},{"id":"m161","de":"cabo","texto":"Quando tem o próximo evento?","hora":"9:07"},{"id":"m162","de":"eleitor","texto":"Pode me mandar o material?","hora":"10:14"},{"id":"m163","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"11:21"},{"id":"m164","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"12:28"},{"id":"m165","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"13:35"},{"id":"m166","de":"eleitor","texto":"Obrigado pelas informações.","hora":"14:42"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-17', 'elt-18', 'Pedro Alves', 'Maiobao', '["provavel","prioridade"]', 0, 'false', '[{"id":"m170","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"8:00"},{"id":"m171","de":"cabo","texto":"Pode me mandar o material?","hora":"9:07"},{"id":"m172","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"10:14"},{"id":"m173","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"11:21"},{"id":"m174","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"12:28"},{"id":"m175","de":"cabo","texto":"Obrigado pelas informações.","hora":"13:35"},{"id":"m176","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"14:42"},{"id":"m177","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"15:49"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-18', 'elt-19', 'Luisa Costa', 'Tambau', '["indeciso","whatsapp"]', 3, 'true', '[{"id":"m180","de":"eleitor","texto":"Pode me mandar o material?","hora":"8:00"},{"id":"m181","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"9:07"},{"id":"m182","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"10:14"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-19', 'elt-20', 'Felipe Dias', 'Vinhais', '["adversario","receptivo"]', 0, 'false', '[{"id":"m190","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"8:00"},{"id":"m191","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"9:07"},{"id":"m192","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"10:14"},{"id":"m193","de":"cabo","texto":"Obrigado pelas informações.","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-20', 'elt-21', 'Juliana Martins', 'Calhau', '["ferrenho","prioridade"]', 0, 'true', '[{"id":"m200","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"8:00"},{"id":"m201","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"9:07"},{"id":"m202","de":"eleitor","texto":"Obrigado pelas informações.","hora":"10:14"},{"id":"m203","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"11:21"},{"id":"m204","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-21', 'elt-22', 'Rafael Oliveira', 'Cohab', '["provavel","whatsapp"]', 2, 'false', '[{"id":"m210","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"8:00"},{"id":"m211","de":"cabo","texto":"Obrigado pelas informações.","hora":"9:07"},{"id":"m212","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"10:14"},{"id":"m213","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"11:21"},{"id":"m214","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"12:28"},{"id":"m215","de":"cabo","texto":"Pode me mandar o material?","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-22', 'elt-23', 'Camila Santos', 'Anil', '["indeciso","receptivo"]', 0, 'true', '[{"id":"m220","de":"eleitor","texto":"Obrigado pelas informações.","hora":"8:00"},{"id":"m221","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"9:07"},{"id":"m222","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"10:14"},{"id":"m223","de":"cabo","texto":"Quando tem o próximo evento?","hora":"11:21"},{"id":"m224","de":"eleitor","texto":"Pode me mandar o material?","hora":"12:28"},{"id":"m225","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"13:35"},{"id":"m226","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"14:42"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-23', 'elt-24', 'Bruno Carvalho', 'Turu', '["adversario","prioridade"]', 0, 'false', '[{"id":"m230","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"8:00"},{"id":"m231","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"9:07"},{"id":"m232","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"10:14"},{"id":"m233","de":"cabo","texto":"Pode me mandar o material?","hora":"11:21"},{"id":"m234","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"12:28"},{"id":"m235","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"13:35"},{"id":"m236","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"14:42"},{"id":"m237","de":"cabo","texto":"Obrigado pelas informações.","hora":"15:49"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-24', 'elt-25', 'Maria Silva', 'Centro', '["ferrenho","whatsapp"]', 1, 'true', '[{"id":"m240","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"8:00"},{"id":"m241","de":"cabo","texto":"Quando tem o próximo evento?","hora":"9:07"},{"id":"m242","de":"eleitor","texto":"Pode me mandar o material?","hora":"10:14"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-25', 'elt-26', 'Joo Souza', 'Maiobao', '["provavel","receptivo"]', 0, 'false', '[{"id":"m250","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"8:00"},{"id":"m251","de":"cabo","texto":"Pode me mandar o material?","hora":"9:07"},{"id":"m252","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"10:14"},{"id":"m253","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-26', 'elt-27', 'Ana Lima', 'Tambau', '["indeciso","prioridade"]', 0, 'true', '[{"id":"m260","de":"eleitor","texto":"Pode me mandar o material?","hora":"8:00"},{"id":"m261","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"9:07"},{"id":"m262","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"10:14"},{"id":"m263","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"11:21"},{"id":"m264","de":"eleitor","texto":"Obrigado pelas informações.","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-27', 'elt-28', 'Carlos Pereira', 'Vinhais', '["adversario","whatsapp"]', 4, 'false', '[{"id":"m270","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"8:00"},{"id":"m271","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"9:07"},{"id":"m272","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"10:14"},{"id":"m273","de":"cabo","texto":"Obrigado pelas informações.","hora":"11:21"},{"id":"m274","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"12:28"},{"id":"m275","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-28', 'elt-29', 'Beatriz Rocha', 'Calhau', '["ferrenho","receptivo"]', 0, 'true', '[{"id":"m280","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"8:00"},{"id":"m281","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"9:07"},{"id":"m282","de":"eleitor","texto":"Obrigado pelas informações.","hora":"10:14"},{"id":"m283","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"11:21"},{"id":"m284","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"12:28"},{"id":"m285","de":"cabo","texto":"Quando tem o próximo evento?","hora":"13:35"},{"id":"m286","de":"eleitor","texto":"Pode me mandar o material?","hora":"14:42"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-29', 'elt-30', 'Pedro Alves', 'Cohab', '["provavel","prioridade"]', 0, 'false', '[{"id":"m290","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"8:00"},{"id":"m291","de":"cabo","texto":"Obrigado pelas informações.","hora":"9:07"},{"id":"m292","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"10:14"},{"id":"m293","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"11:21"},{"id":"m294","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"12:28"},{"id":"m295","de":"cabo","texto":"Pode me mandar o material?","hora":"13:35"},{"id":"m296","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"14:42"},{"id":"m297","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"15:49"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-30', 'elt-31', 'Luisa Costa', 'Anil', '["indeciso","whatsapp"]', 3, 'true', '[{"id":"m300","de":"eleitor","texto":"Obrigado pelas informações.","hora":"8:00"},{"id":"m301","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"9:07"},{"id":"m302","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"10:14"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-31', 'elt-32', 'Felipe Dias', 'Turu', '["adversario","receptivo"]', 0, 'false', '[{"id":"m310","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"8:00"},{"id":"m311","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"9:07"},{"id":"m312","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"10:14"},{"id":"m313","de":"cabo","texto":"Pode me mandar o material?","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-32', 'elt-33', 'Juliana Martins', 'Centro', '["ferrenho","prioridade"]', 0, 'true', '[{"id":"m320","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"8:00"},{"id":"m321","de":"cabo","texto":"Quando tem o próximo evento?","hora":"9:07"},{"id":"m322","de":"eleitor","texto":"Pode me mandar o material?","hora":"10:14"},{"id":"m323","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"11:21"},{"id":"m324","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-33', 'elt-34', 'Rafael Oliveira', 'Maiobao', '["provavel","whatsapp"]', 2, 'false', '[{"id":"m330","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"8:00"},{"id":"m331","de":"cabo","texto":"Pode me mandar o material?","hora":"9:07"},{"id":"m332","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"10:14"},{"id":"m333","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"11:21"},{"id":"m334","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"12:28"},{"id":"m335","de":"cabo","texto":"Obrigado pelas informações.","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-34', 'elt-35', 'Camila Santos', 'Tambau', '["indeciso","receptivo"]', 0, 'true', '[{"id":"m340","de":"eleitor","texto":"Pode me mandar o material?","hora":"8:00"},{"id":"m341","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"9:07"},{"id":"m342","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"10:14"},{"id":"m343","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"11:21"},{"id":"m344","de":"eleitor","texto":"Obrigado pelas informações.","hora":"12:28"},{"id":"m345","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"13:35"},{"id":"m346","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"14:42"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-35', 'elt-36', 'Bruno Carvalho', 'Vinhais', '["adversario","prioridade"]', 0, 'false', '[{"id":"m350","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"8:00"},{"id":"m351","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"9:07"},{"id":"m352","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"10:14"},{"id":"m353","de":"cabo","texto":"Obrigado pelas informações.","hora":"11:21"},{"id":"m354","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"12:28"},{"id":"m355","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"13:35"},{"id":"m356","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"14:42"},{"id":"m357","de":"cabo","texto":"Pode me mandar o material?","hora":"15:49"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-36', 'elt-37', 'Maria Silva', 'Calhau', '["ferrenho","whatsapp"]', 1, 'true', '[{"id":"m360","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"8:00"},{"id":"m361","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"9:07"},{"id":"m362","de":"eleitor","texto":"Obrigado pelas informações.","hora":"10:14"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-37', 'elt-38', 'Joo Souza', 'Cohab', '["provavel","receptivo"]', 0, 'false', '[{"id":"m370","de":"eleitor","texto":"Qual o número da seção pra votar?","hora":"8:00"},{"id":"m371","de":"cabo","texto":"Obrigado pelas informações.","hora":"9:07"},{"id":"m372","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"10:14"},{"id":"m373","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"11:21"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-38', 'elt-39', 'Ana Lima', 'Anil', '["indeciso","prioridade"]', 0, 'true', '[{"id":"m380","de":"eleitor","texto":"Obrigado pelas informações.","hora":"8:00"},{"id":"m381","de":"cabo","texto":"Minha vizinha também quer participar.","hora":"9:07"},{"id":"m382","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"10:14"},{"id":"m383","de":"cabo","texto":"Quando tem o próximo evento?","hora":"11:21"},{"id":"m384","de":"eleitor","texto":"Pode me mandar o material?","hora":"12:28"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-39', 'elt-40', 'Carlos Pereira', 'Turu', '["adversario","whatsapp"]', 4, 'false', '[{"id":"m390","de":"eleitor","texto":"Minha vizinha também quer participar.","hora":"8:00"},{"id":"m391","de":"cabo","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"9:07"},{"id":"m392","de":"eleitor","texto":"Quando tem o próximo evento?","hora":"10:14"},{"id":"m393","de":"cabo","texto":"Pode me mandar o material?","hora":"11:21"},{"id":"m394","de":"eleitor","texto":"Não vou poder na visita de amanhã.","hora":"12:28"},{"id":"m395","de":"cabo","texto":"Apoio sim, conte comigo!","hora":"13:35"}]');
INSERT IGNORE INTO `conversas` (`id`, `eleitor_id`, `nome`, `bairro`, `tags`, `nao_lidas`, `online`, `mensagens`) VALUES ('conv-40', 'elt-41', 'Beatriz Rocha', 'Centro', '["ferrenho","receptivo"]', 0, 'true', '[{"id":"m400","de":"eleitor","texto":"Bom dia! Vi a campanha no bairro, curti as propostas.","hora":"8:00"},{"id":"m401","de":"cabo","texto":"Quando tem o próximo evento?","hora":"9:07"},{"id":"m402","de":"eleitor","texto":"Pode me mandar o material?","hora":"10:14"},{"id":"m403","de":"cabo","texto":"Não vou poder na visita de amanhã.","hora":"11:21"},{"id":"m404","de":"eleitor","texto":"Apoio sim, conte comigo!","hora":"12:28"},{"id":"m405","de":"cabo","texto":"Qual o número da seção pra votar?","hora":"13:35"},{"id":"m406","de":"eleitor","texto":"Obrigado pelas informações.","hora":"14:42"}]');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-1', 'Aluguel de palco', 'Eventos', 'despesa', 1083, '2026-02-02T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-2', 'Financiamento coletivo', 'Logística', 'receita', 1816, '2026-03-03T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-3', 'Tráfego pago Instagram', 'Pessoal', 'despesa', 2549, '2026-04-04T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-4', 'Doação de campanha — Pessoa Física', 'Doações', 'receita', 3282, '2026-05-05T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-5', 'Transporte de voluntários', 'Marketing', 'despesa', 4015, '2026-06-06T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-6', 'Financiamento coletivo', 'Eventos', 'receita', 4748, '2026-01-07T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-7', 'Aluguel de palco', 'Logística', 'despesa', 5481, '2026-02-08T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-8', 'Doação de campanha — Pessoa Física', 'Pessoal', 'receita', 6214, '2026-03-09T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-9', 'Tráfego pago Instagram', 'Doações', 'despesa', 6947, '2026-04-10T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-10', 'Financiamento coletivo', 'Marketing', 'receita', 7680, '2026-05-11T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-11', 'Transporte de voluntários', 'Eventos', 'despesa', 8413, '2026-06-12T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-12', 'Doação de campanha — Pessoa Física', 'Logística', 'receita', 9146, '2026-01-13T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-13', 'Aluguel de palco', 'Pessoal', 'despesa', 9879, '2026-02-14T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-14', 'Financiamento coletivo', 'Doações', 'receita', 10612, '2026-03-15T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-15', 'Tráfego pago Instagram', 'Marketing', 'despesa', 11345, '2026-04-16T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-16', 'Doação de campanha — Pessoa Física', 'Eventos', 'receita', 12078, '2026-05-17T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-17', 'Transporte de voluntários', 'Logística', 'despesa', 12811, '2026-06-18T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-18', 'Financiamento coletivo', 'Pessoal', 'receita', 13544, '2026-01-19T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-19', 'Aluguel de palco', 'Doações', 'despesa', 14277, '2026-02-20T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-20', 'Doação de campanha — Pessoa Física', 'Marketing', 'receita', 15010, '2026-03-21T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-21', 'Tráfego pago Instagram', 'Eventos', 'despesa', 15743, '2026-04-22T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-22', 'Financiamento coletivo', 'Logística', 'receita', 16476, '2026-05-23T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-23', 'Transporte de voluntários', 'Pessoal', 'despesa', 17209, '2026-06-24T03:00:00.000Z');
INSERT IGNORE INTO `movimentacoes` (`id`, `descricao`, `categoria`, `tipo`, `valor`, `data`) VALUES ('fin-24', 'Doação de campanha — Pessoa Física', 'Doações', 'receita', 17942, '2026-01-25T03:00:00.000Z');
INSERT IGNORE INTO `notificacoes` (`id`, `titulo`, `corpo`, `tempo`, `lida`, `tipo`) VALUES ('n1', 'Nova liderança cadastrada', 'Carla Mendes entrou na equipe de Santana.', '2026-06-08T10:00:00', 'false', 'success');
INSERT IGNORE INTO `notificacoes` (`id`, `titulo`, `corpo`, `tempo`, `lida`, `tipo`) VALUES ('n2', 'Meta de bairro em risco', 'Itaquera está 18% abaixo da meta semanal.', '2026-06-07T18:30:00', 'false', 'warning');
INSERT IGNORE INTO `notificacoes` (`id`, `titulo`, `corpo`, `tempo`, `lida`, `tipo`) VALUES ('n3', 'Visita cancelada', 'Eleitor José Souza cancelou a visita de amanhã.', '2026-06-07T14:10:00', 'true', 'danger');
INSERT IGNORE INTO `notificacoes` (`id`, `titulo`, `corpo`, `tempo`, `lida`, `tipo`) VALUES ('n4', 'Pesquisa concluída', 'Intenção de voto 1º turno apurada com 1.840 entrevistas.', '2026-06-06T09:00:00', 'true', 'info');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-1', 'Joo Souza', 'atualizou', 'um cabo', '2026-06-02T12:07:00.000Z', 'update');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-2', 'Ana Lima', 'converteu', 'a pesquisa 1º turno', '2026-06-03T13:14:00.000Z', 'message');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-3', 'Carlos Pereira', 'agendou visita para', 'o evento de sábado', '2026-06-04T14:21:00.000Z', 'visit');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-4', 'Beatriz Rocha', 'enviou mensagem para', 'a liderança de Mooca', '2026-06-05T15:28:00.000Z', 'event');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-5', 'Pedro Alves', 'marcou como apoio', 'um eleitor indeciso', '2026-06-06T16:35:00.000Z', 'create');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-6', 'Luisa Costa', 'reabriu', '12 eleitores', '2026-06-07T17:42:00.000Z', 'update');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-7', 'Felipe Dias', 'cadastrou', 'um cabo', '2026-06-08T18:49:00.000Z', 'message');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-8', 'Juliana Martins', 'atualizou', 'a pesquisa 1º turno', '2026-06-01T19:56:00.000Z', 'visit');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-9', 'Rafael Oliveira', 'converteu', 'o evento de sábado', '2026-06-02T20:03:00.000Z', 'event');
INSERT IGNORE INTO `atividades` (`id`, `usuario`, `acao`, `alvo`, `tempo`, `tipo`) VALUES ('atv-10', 'Camila Santos', 'agendou visita para', 'a liderança de Mooca', '2026-06-03T21:10:00.000Z', 'create');
