/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppVisitasRouteImport } from './routes/_app.visitas'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPesquisasRouteImport } from './routes/_app.pesquisas'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppMapaRouteImport } from './routes/_app.mapa'
import { Route as AppLiderancasRouteImport } from './routes/_app.liderancas'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppEventosRouteImport } from './routes/_app.eventos'
import { Route as AppEquipeRouteImport } from './routes/_app.equipe'
import { Route as AppEleitoresRouteImport } from './routes/_app.eleitores'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppCabosRouteImport } from './routes/_app.cabos'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitasRoute = AppVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPesquisasRoute = AppPesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppLiderancasRoute = AppLiderancasRouteImport.update({
  id: '/liderancas',
  path: '/liderancas',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppEleitoresRoute = AppEleitoresRouteImport.update({
  id: '/eleitores',
  path: '/eleitores',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppCabosRoute = AppCabosRouteImport.update({
  id: '/cabos',
  path: '/cabos',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AppAgendaRoute
  '/cabos': typeof AppCabosRoute
  '/campanhas': typeof AppCampanhasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/eleitores': typeof AppEleitoresRoute
  '/equipe': typeof AppEquipeRoute
  '/eventos': typeof AppEventosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/liderancas': typeof AppLiderancasRoute
  '/mapa': typeof AppMapaRoute
  '/perfil': typeof AppPerfilRoute
  '/pesquisas': typeof AppPesquisasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/visitas': typeof AppVisitasRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AppAgendaRoute
  '/cabos': typeof AppCabosRoute
  '/campanhas': typeof AppCampanhasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/eleitores': typeof AppEleitoresRoute
  '/equipe': typeof AppEquipeRoute
  '/eventos': typeof AppEventosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/liderancas': typeof AppLiderancasRoute
  '/mapa': typeof AppMapaRoute
  '/perfil': typeof AppPerfilRoute
  '/pesquisas': typeof AppPesquisasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/visitas': typeof AppVisitasRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/cabos': typeof AppCabosRoute
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eleitores': typeof AppEleitoresRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/eventos': typeof AppEventosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/liderancas': typeof AppLiderancasRoute
  '/_app/mapa': typeof AppMapaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pesquisas': typeof AppPesquisasRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/visitas': typeof AppVisitasRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/cabos'
    | '/campanhas'
    | '/configuracoes'
    | '/dashboard'
    | '/eleitores'
    | '/equipe'
    | '/eventos'
    | '/financeiro'
    | '/liderancas'
    | '/mapa'
    | '/perfil'
    | '/pesquisas'
    | '/relatorios'
    | '/visitas'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/cabos'
    | '/campanhas'
    | '/configuracoes'
    | '/dashboard'
    | '/eleitores'
    | '/equipe'
    | '/eventos'
    | '/financeiro'
    | '/liderancas'
    | '/mapa'
    | '/perfil'
    | '/pesquisas'
    | '/relatorios'
    | '/visitas'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/agenda'
    | '/_app/cabos'
    | '/_app/campanhas'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/eleitores'
    | '/_app/equipe'
    | '/_app/eventos'
    | '/_app/financeiro'
    | '/_app/liderancas'
    | '/_app/mapa'
    | '/_app/perfil'
    | '/_app/pesquisas'
    | '/_app/relatorios'
    | '/_app/visitas'
    | '/_app/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visitas': {
      id: '/_app/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof AppVisitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesquisas': {
      id: '/_app/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof AppPesquisasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liderancas': {
      id: '/_app/liderancas'
      path: '/liderancas'
      fullPath: '/liderancas'
      preLoaderRoute: typeof AppLiderancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos': {
      id: '/_app/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleitores': {
      id: '/_app/eleitores'
      path: '/eleitores'
      fullPath: '/eleitores'
      preLoaderRoute: typeof AppEleitoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cabos': {
      id: '/_app/cabos'
      path: '/cabos'
      fullPath: '/cabos'
      preLoaderRoute: typeof AppCabosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppCabosRoute: typeof AppCabosRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEleitoresRoute: typeof AppEleitoresRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppEventosRoute: typeof AppEventosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppLiderancasRoute: typeof AppLiderancasRoute
  AppMapaRoute: typeof AppMapaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPesquisasRoute: typeof AppPesquisasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVisitasRoute: typeof AppVisitasRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppCabosRoute: AppCabosRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEleitoresRoute: AppEleitoresRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppEventosRoute: AppEventosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppLiderancasRoute: AppLiderancasRoute,
  AppMapaRoute: AppMapaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPesquisasRoute: AppPesquisasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVisitasRoute: AppVisitasRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
